# Generated by Django 3.2.16 on 2023-01-30 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
