# Generated by Django 4.1.3 on 2023-01-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='meta_description',
            field=models.TextField(blank=True, null=True, verbose_name='description meta'),
        ),
        migrations.AddField(
            model_name='issue',
            name='meta_keyword',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Keywords meta'),
        ),
        migrations.AddField(
            model_name='issue',
            name='meta_title',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='titre meta'),
        ),
    ]
