# Generated by Django 3.2.16 on 2023-01-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date de publication'),
        ),
    ]
