# Generated by Django 3.2.16 on 2023-01-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='to_home_page',
            field=models.BooleanField(default=False, verbose_name="ajouter a la page d'accueil"),
        ),
    ]
