# Generated by Django 4.1.3 on 2022-12-12 10:58

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_article_category_category_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="article",
            name="description",
        ),
        migrations.AddField(
            model_name="article",
            name="actif",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="article",
            name="description_max",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Description totale de l'article"
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="description_min",
            field=models.TextField(
                default="", verbose_name="Description minimale de l'article"
            ),
        ),
    ]
