# Generated by Django 3.2.16 on 2023-01-24 08:19

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20230123_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='texte_image',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='texte deux colonnes'),
        ),
    ]
