# Generated by Django 4.1.3 on 2022-12-12 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_remove_article_description_article_actif_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="description_min",
            field=models.CharField(
                default="",
                max_length=500,
                verbose_name="Description minimale de l'article",
            ),
        ),
    ]
