# Generated by Django 3.2.16 on 2023-01-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_article_texte_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='en_avant',
            field=models.BooleanField(default=False, verbose_name="mettre en avant a la page d'accueil"),
        ),
        migrations.AlterField(
            model_name='issue',
            name='title',
            field=models.CharField(max_length=254, verbose_name='Titre du Numéro'),
        ),
    ]
