# Generated by Django 4.1.3 on 2022-12-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_article_description_min"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="description_min",
            field=models.TextField(blank=True, null=True),
        ),
    ]
