# Generated by Django 3.2.16 on 2023-01-25 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_role_active'),
        ('core', '0007_auto_20230124_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='autors', to='account.Profile', verbose_name='Auteur'),
        ),
    ]
