# Generated by Django 4.1.3 on 2022-12-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_alter_article_description_min"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="article",
            name="description_min",
            field=models.TextField(
                blank=True, null=True, verbose_name="Description minimale de l'article"
            ),
        ),
    ]
