# Generated by Django 4.1.3 on 2022-12-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_image_description_alter_article_description_min"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_of_article",
                to="core.category",
                verbose_name="categorie de l'article",
            ),
        ),
    ]
