# Generated by Django 3.2.16 on 2023-01-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='aperçu',
            new_name='apercu',
        ),
    ]
