# Generated by Django 3.2.16 on 2023-01-30 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_aperçu_article_apercu'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='apercu',
            new_name='aperçu',
        ),
    ]
