# Generated by Django 3.2.16 on 2023-01-30 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_delete_user'),
        ('core', '0011_rename_apercu_article_aperçu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ManyToManyField(blank=True, null=True, related_name='autors', to='account.Profile', verbose_name='Auteur'),
        ),
    ]
