# Generated by Django 3.2.16 on 2023-01-30 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_article_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='author',
            new_name='authors',
        ),
    ]
