# Generated by Django 3.2.16 on 2023-02-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_article_authors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='aperçu',
        ),
        migrations.AddField(
            model_name='article',
            name='apercu',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='apercu'),
        ),
    ]
