# Generated by Django 3.2.16 on 2023-02-07 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile_actif'),
        ('core', '0015_auto_20230206_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='articles_of_authors', to='account.Profile', verbose_name='Auteur'),
        ),
    ]
