# Generated by Django 3.2.16 on 2023-03-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_article_authors'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='side',
            field=models.BooleanField(default=False, verbose_name='side picture '),
        ),
    ]
