# Generated by Django 3.2.12 on 2023-04-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_articleimage_side'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date de Création')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Date de dernière mise à jour')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='job title')),
                ('slug', models.CharField(max_length=150, verbose_name='job url')),
                ('description', models.TextField(blank=True, null=True, verbose_name='experience')),
                ('type', models.CharField(choices=[('FULLTIME', 'دوام كامل'), ('PART_TIME', 'دوام جزئي'), ('INTERNSHIP', 'فترة تدريبية'), ('TEMPORARY', 'مؤقت')], default='TEMPORARY', max_length=20, verbose_name='Job type')),
                ('budget', models.DecimalField(decimal_places=2, max_digits=5)),
                ('duration', models.IntegerField(blank=True, null=True, verbose_name='Number of days')),
                ('expiration', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='core.Tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Annonce',
            },
        ),
    ]
