# Generated by Django 3.2.12 on 2023-04-06 09:30

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_job_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='experience'),
        ),
    ]
